### ISSUE TITLE
Cannot add reference to MathNet.Numerics.MKL.dll

### ISSUE THREAD

**Issue by tibel** [mathnet/mathnet-numerics-native#13]
I get an error message from visual studio when I try to add _MathNet.Numerics.MKL.dll_ assembly reference (running VS2012 Update 2) using current nuget package.

![mathnet_native_error](https://f.cloud.github.com/assets/387395/495715/80285e3e-bbcf-11e2-8411-5d0eb402b35a.png)

Happens with x86 and x64 version. Is there any known issue with current nuget release?

**Comment by cuda** [comment]
Since those are native libraries you don't add them as assembly references. Just add them as project items and have VS copy them to the output directory on build.

**Comment by tibel** [comment]
You are right.
Thank you, I was thinking a bit weird.
