### ISSUE TITLE
Redistribution license

### ISSUE THREAD

**Issue by zippy1981** [mathnet/mathnet-numerics-native#14]
The [MKL FAQ](http://software.intel.com/en-us/intel-mkl/) says you can redistribute software created with this DLL. It doesn't explicitly mention libraries that use the library. Did you ever ask intel about this, and can you update the README with the answer?

**Comment by cdrnet** [comment]
I agree, we should clarify this directly with Intel, to make sure using our packages cannot accidentally get you into legal trouble. Up to now I was under the impression that the right to redistribute is bound to the license and thus to us (and therefore does _not_ give users a right to redistribute as well, i.e. if they want to include it in a commercial product they'd need a license themselves as well), but this is not actually backed with Intel and might be wrong.

**Comment by cdrnet** [comment]
Also, we should clarify the license info in the MKL NuGet packages, it is somewhat misleading right now.
