### ISSUE TITLE
Single mixed mode dll with Math.NET Numerics and MKL library

### ISSUE THREAD

**Issue by zippy1981** [mathnet/mathnet-numerics-native#15]
[System.Data.Sqlite.dll](http://system.data.sqlite.org/index.html/doc/trunk/www/downloads.wiki) is a midex mode dll that includes the unmanaged C driver, and the .NET ADO.NET provider. Would you consider bundling the native providers as a single DLL in this manner?

**Comment by cdrnet** [comment]
We actually tried something like this but failed some time ago. Maybe we can try again with MKL 11. Do you have experience building such dlls?

**Comment by zippy1981** [comment]
No I don't. I can give it a try though.
