### ISSUE TITLE
Default Provider by Environment Variable?

### ISSUE THREAD

**Issue by cdrnet** [mathnet/mathnet-numerics-native#5]
Related to #4, I wonder whether we shouldn't allow the default provider to be chosen by environment variables, if there are any set? For testing all the native providers this would be useful as well, since it's easy to set environment variables in a shell script, build file (I think?) and especially so in TeamCity (so we could automatically run the full suite against all providers). It would also make it possible to get rid of the test hack that is still needed to configure the right provider before starting.

Any thoughts?

@cuda @tibel

**Comment by cuda** [comment]
That might work well. Put a static constructor in the Control class to check for the variable. If it doesn't exist, then use the managed provider. Users could still override it in their code. It would simplify testing nicely without using an NUnit extension.

**Comment by tibel** [comment]
I would prefer to have the environment variable only in the tests.

If it is in `Control` class, someone can break my Application by changing a users environment variable. The application would become vulnerable.

**Comment by cuda** [comment]
I disagree. Setting environment variables is an acceptable, standard way to control application behavior.

**Comment by cuda** [comment]
and to add, an application could always use an app.config file and corresponding code to override the environment variable.

**Comment by tibel** [comment]
Didn't thought on this. You are right. Should not be a problem.

**Comment by cdrnet** [comment]
Great, thanks for the feedback!

**Comment by cdrnet** [comment]
@cuda using environment variables, you no longer need the unit test config file (and corresponding code) then and I can drop it, correct?

**Comment by cuda** [comment]
Right. We can also drop the mkl wrapper test project from the native wrapper project.
